parameters:
   ikantam.utils.twig.extensions.class: iKantam\UtilsBundle\Twig\UtilsExtension

services:
     ikantam.utils.twig.extensions:
        class: %ikantam.utils.twig.extensions.class%
        arguments: [@service_container]
        tags:
            - { name: twig.extension }